### ISSUE TITLE
[Feature Requests] Accept options in the placeholder

### ISSUE THREAD

**Issue by petrkrejcik** [nagaozen/markdown-it-toc-done-right#16] opened 2019-07-13 19:55 UTC
I would like to pass some options directly to the placeholder:
```
[toc level=2]
```

It would allow us to set different settings per note in the note taking app [Joplin](https://github.com/laurent22/joplin).

Would that be possible?

**Comment by nagaozen** [comment] 2019-07-14 00:45
Currently, this is incredibly hard to do because we have a regexp to match the most common notations people are using. That said, I really like this idea, something like inline options to overwrite the given in javascript. If you make a PR I'll merge

**Comment by laurent22** [comment] 2019-07-14 12:49
@nagaozen, I guess we'd just need to add room for these options in [this regex](https://github.com/nagaozen/markdown-it-toc-done-right/blob/master/index.js#L27)? Or is there some additional difficulty?

**Comment by nagaozen** [comment] 2019-07-14 14:56
The additional difficulty is to validate there's an inline json there...

**Comment by tessus** [comment] 2019-07-14 20:56
Hmm, ok. I would have just used a different notation. Thus add the following to the regex `|\[toc (.*)\]`.
Then we can take`\1` or whatever is used in js to reference the backreference and split it further into commands. Or even better, use json decode for that part (`\1`) to create an array. If that fails, the json was not valid and thus the options used were not vallid either.

**Comment by nagaozen** [comment] 2019-07-17 18:35
> 
> 
> Hmm, ok. I would have just used a different notation. Thus add the following to the regex `|\[toc (.*)\]`.
> Then we can take`\1` or whatever is used in js to reference the backreference and split it further into commands. Or even better, use json decode for that part (`\1`) to create an array. If that fails, the json was not valid and thus the options used were not vallid either.

This kind of makes sense for me... we can match anything that's not the "end of the regular expression". Like `\[TOC ([^\\])+\]` and try to JSON.parse it inside a try, then assign it to the given options if parsed, ignore otherwise... Now the only problem is: what to do with expressions that use more than a character to indicate the pattern end? Things like `[? TOC ?]` or `<%= TOC %>`. I always end up thinking it would require a DSL, but it seems like a cannon to kill fly.

**Comment by nagaozen** [comment] 2019-07-17 18:37
And yes, another option is to require a complete different notation for this special case, like `#!$<TOC\s([^}]+)>`

**Comment by tessus** [comment] 2019-07-17 21:37
I rather meant that we accept only options for `[toc]`, in which case we only have to append the regex I suggested (or the one you did).
This would be the eaiest an most user friendly way. If users wanted to override options they would have to change the toc call anyway, so there's no problem in using `[toc options-here]`.

**Comment by nagaozen** [comment] 2019-07-18 13:03
Oh, right, makes sense ... but I prefer to go with some starting and ending characters that doesn't belong to json. gedit snippets have a great placeholder that enables using python inline it's like `$<[1]: return split[0].capitalize()>` <https://wiki.gnome.org/Apps/Gedit/Plugins/Snippets>. It's a good choice for us too.

**Comment by tessus** [comment] 2019-07-18 16:42
Whatever gets the job done.

> but I prefer to go with some starting and ending characters that doesn't belong to json.

I guess it's a personal preference. The regex takes care of the start and end character anyway, so it does not matter at all, but it's obviously your choice.

**Comment by nagaozen** [comment] 2019-07-23 14:52
I made a try in this feature and I'd it working with some constraints:

- it won't accept spaces inside the JSON
- it won't accept changing the `slugify` function, because the inline options are JSON compatible
- it won't accept the characted '}' inside the inline options
- changing level, as suggested in the initial request, will break `markdown-it-anchor`when the same content is used in many headers. _e.g._ `# header\n\n## header\n\n###header`

Anyone want to try? Are the constraints reasonable?

**Comment by tessus** [comment] 2019-07-24 03:36
This is great news. I want to test it, but I will be away for the next few days.

The constrainsts are mostly reasonable, I think, although I'm not sure why spaces should not be supported, but it's not really important. The only issue might be the last item where you mentioned that it could break `markdown-it-anchor`.

So how could we now use a toc with only 3 levels? Would it be: `$<toc{"level":[1,2,3]}>`?
How can we set 2 options? Like this? `$<toc{"level":[1,2,3],"listType":"ul"}>`

In any case, I will test it as soon as I'm back.

**Comment by nagaozen** [comment] 2019-07-24 03:42
> 
> 
> This is great news. I want to test it, but I will be away for the next few days.
> 
> The constrainsts are mostly reasonable, I think, although I'm not sure why spaces should not be supported, but it's not really important. The only issue might be the last item where you mentioned that it could break `markdown-it-anchor`.
> 
> So how could we now use a toc with only 3 levels? Would it be: `$<toc{"level":[1,2,3]}>`?
> How can we set 2 options? Like this? `$<toc{"level":[1,2,3],"listType":"ul"}>`
> 
> In any case, I will test it as soon as I'm back.

Yep, exactly as you did.

**Comment by tessus** [comment] 2019-08-02 04:38
Ok, I ran a few tests with Joplin using your new branch.

I've noticed a few things that seemed odd to me. We are using `listType: ul` by default, so I'm not sure, if this is a bug or not.

# listType ol

`$<toc{"listType":"ol"}>` produces the following TOC:

<img width="217" alt="image" src="https://user-images.githubusercontent.com/223439/62344246-40c44780-b4bb-11e9-8e90-c7054c43b41d.png">

Shouldn't the numbering show the hierarchy? Like the numbers in the title?

# new toc syntax and then in the same file an old syntax

```
$<toc{"level":[1,2],"listType":"ul"}>

---

[toc]
```

produces the following TOCs:

<img width="153" alt="image" src="https://user-images.githubusercontent.com/223439/62344517-4ff7c500-b4bc-11e9-8407-785c9fecf1af.png">

It seems that the second `[toc]` inherits the options of the first one. Is this intended? IMO, the `[toc]` should use the default values to create the toc.

# several new toc syntax entries - last one wins

```
$<toc{"level":[1],"listType":"ul"}>

---

$<toc{"level":[1,2],"listType":"ol"}>

---

[toc]
```

produces the following TOCs:

<img width="159" alt="image" src="https://user-images.githubusercontent.com/223439/62344699-170c2000-b4bd-11e9-80e2-f9ec91bc8d8a.png">

IMO every output should be different, but they are all the same. It seems that the last one with the new syntax is used for all of them.

# Misc

Other than that it works and I'm quite happy. It's just possible that people might use several toc placeholders within one file and the current behavior is rather confusing.

**Comment by nagaozen** [comment] 2019-08-02 21:28
What a great review! Thank you!

## listType `ol`

> Shouldn't the numbering show the hierarchy? Like the numbers in the title?

It's not a bug, just the way `ol` works. You can check this by visiting this example in codepen <https://codepen.io/anon/pen/aeLZXe>.

## new toc syntax and then in the same file an old syntax

> It seems that the second [toc] inherits the options of the first one. Is this intended? IMO, the `[toc]` should use the default values to create the toc.

It is intended, when the first "overwrite placeholder" is detected, it's used to overwrite the options given to the plugin instance. It's basically a way to overwrite the options inline. But I agree with you that changing it only locally seems elegant. I'll take a look to see if thats possible.

The last question is related with the second one.

Best,
nagaozen

**Comment by tessus** [comment] 2019-08-02 21:44
> It's not a bug, just the way `ol` works.

Thanks, I almost thought so. I never really used `ol`, so I didn't know. Now I do. Thanks for the info.

> I'll take a look to see if thats possible.

That would be really great. But if it were not, this behavior should be mentioned in the doc.

> The last question is related with the second one.

Yep, I just wanted to mention it for completeness. It only shows that the last one (of the new syntax) wins and is then used globally.

**Comment by tessus** [comment] 2019-10-17 06:57
@nagaozen just curious. What is the status of this? Except the fact that I can't use more than one toc in a document (unless I want them to all look the same - like the first one), the https://github.com/nagaozen/markdown-it-toc-done-right/tree/inline_options branch works great.

**Comment by nagaozen** [comment] 2019-10-17 14:50
Hi @tessus, I'm working on this today, implemented the callback option and trying a different approach to only change the options inplace, if it works will use that, if not, i'll merge that inline_options branch.

**Comment by nagaozen** [comment] 2019-10-17 14:51
Because I fixed the issues at `markdown-it-anchor` I'd to update the tests.

**Comment by tessus** [comment] 2019-10-17 22:12
Thanks for the info. No rush, I really was just curious.

**Closed** 2019-10-18 03:08 UTC

**Comment by nagaozen** [comment] 2019-10-18 03:10
Implemented on 4.1.0

**Comment by tessus** [comment] 2019-10-18 03:23
Brilliant, thanks.

**Comment by tessus** [comment] 2020-09-27 02:55
@nagaozen Did you remove that option again?

e.g. `$<toc{"listType":"ul"}>` does no longer work.

**Comment by tessus** [comment] 2020-09-27 03:09
@nagaozen never mind the previous comment (which I have deleted). I screwed up. All good.
